### ISSUE TITLE
No vis.py in /demo

### ISSUE THREAD

**Issue by PhilNikitin** [xiu-cs/IGANet#1]
Hello! Great work!

Trying to run demo code, but don't see vis.py in demo folder.

**Comment by xiu-cs** [comment]
Thank you for reminding me. I have updated the vis.py file. Thank you very much. If you have any further questions, please do not hesitate to contact me.

**Comment by PhilNikitin** [comment]
Thank you!

https://user-images.githubusercontent.com/9539501/235966718-500f00a0-f34a-43e2-a0f1-4629c410e35f.mp4

**Comment by Ph-Xu** [comment]
![2`MPQQFWAKD X2X}XNE%%9Q](https://github.com/xiu-cs/IGANet/assets/65990771/9aeb1ef1-4dec-4159-abaf-01a317fa19d2)
yun'x'n
运行demo报错了 这个是因为？
