### ISSUE TITLE
你好，我有两个问题想问你一下

### ISSUE THREAD

**Issue by wangdazhong1112** [xiu-cs/IGANet#2]
1.邻接矩阵的这个4是否代表4帧呢？
![image](https://github.com/xiu-cs/IGANet/assets/119930848/ce737cf1-959a-4644-84f0-97f738d32cd3)
2.骨骼拓扑结构是否存在一些问题？原始代码中不存在下面两行，似乎是骨骼的7关节点直接连接到双臂，而不是8节点
![image](https://github.com/xiu-cs/IGANet/assets/119930848/58a3f7ab-211b-4376-a7f1-8bb3e80bc3b8)

**Comment by wangdazhong1112** [comment]
不好意思！我发现了adj之所以是4,17,17的形状是因为代表了4个不同类型的邻接矩阵，跟帧数无关，但是你为什么不用adj_mx_from_skeleton(skeleton)这种获得邻接矩阵的方式呢？这两个有什么不同？

**Comment by xiu-cs** [comment]
感谢关注！ 提出的问题很细致！
问题1你想你应该已经清楚了，adj_mx_from_skeleton(skeleton)获得的邻接矩阵仅是相邻关系，不包含骨架的对称等结构信息。
对于问题2， 在执行完 self.remove_joints([...])函数后，得到的骨架确实是关节点7连接到双臂的结构，下面两行代码是将左右双臂改成连接到关节点8. 
对于注释“Fix children error”下面的两行代码，应该是你自己写的，确实这里在更改双臂连接点后，没有进一步更新子节点的信息，很好的发现！其实这里做的修复，只需要将节点8的子节点增加11和14这两个即可。

**Comment by xiu-cs** [comment]
感谢关注！ 提出的问题很细致！
问题1你想你应该已经清楚了，adj_mx_from_skeleton(skeleton)获得的邻接矩阵仅是相邻关系，不包含骨架的对称等结构信息。
对于问题2， 在执行完 self.remove_joints([...])函数后，得到的骨架确实是关节点7连接到双臂的结构，下面两行代码是将左右双臂改成连接到关节点8.
对于注释“Fix children error”下面的两行代码，应该是你自己写的，确实这里在更改双臂连接点后，没有进一步更新子节点的信息，很好的发现！其实这里做的修复，只需要将节点8的子节点增加11和14这两个即可。
