### ISSUE TITLE
demo运行出错

### ISSUE THREAD

**Issue by Ph-Xu** [xiu-cs/IGANet#3]
![image](https://github.com/xiu-cs/IGANet/assets/65990771/f91a8394-028a-407a-a4eb-2c3d65ca3af3)
如图所示

**Comment by xiu-cs** [comment]
你好，可以提供更详细的报错信息吗，比如报错位置keypoints的具体维度。

**Comment by Ph-Xu** [comment]
这个没打印出来，我没有改代码任何地方，只是装了对应环境和下载了要求的权重等文件（放到了对应目录下），然后测试demo图片就出现了这个错。

**Comment by Ph-Xu** [comment]
![Uploading image.png…]()
空的

**Comment by Ph-Xu** [comment]
![image](https://github.com/xiu-cs/IGANet/assets/65990771/9c718969-b997-417b-9087-1f07b455dde1)
空的

**Comment by xiu-cs** [comment]
> 

可以打印出来看看呢

**Comment by xiu-cs** [comment]
> ![image](https://user-images.githubusercontent.com/65990771/239159465-9c718969-b997-417b-9087-1f07b455dde1.png) 空的

你这个是对图形进行可视化吗 看样子是没有检测到2D关节点。  看下图形或者视频的路径有没有问题

**Comment by Ph-Xu** [comment]
是的 图形和视频路径用了绝对路径也还是不行 报同样的错  yolo3 包括别的那几个权重就放到对应文件夹下面就好，不用改配置路径吗

**Comment by xiu-cs** [comment]
> 是的 图形和视频路径用了绝对路径也还是不行 报同样的错 yolo3 包括别的那几个权重就放到对应文件夹下面就好，不用改配置路径吗



> 是的 图形和视频路径用了绝对路径也还是不行 报同样的错 yolo3 包括别的那几个权重就放到对应文件夹下面就好，不用改配置路径吗

你往前面回溯下，看下image有没有成功被加载。 可能单纯是image读取的问题
