### ISSUE TITLE
How to reproduce the result with the gt 2D input?

### ISSUE THREAD

**Issue by cocoshe** [xiu-cs/IGANet#8]
My script here:
```shell
python main.py --reload --previous_dir "./pre_trained_model" --model model_IGANet --layers 3 --gpu 2 -k gt
```

The `-k` now is `gt`, but here is my result:

```
===Action=== ==p#1 mm== =p#2 mm=
Directions    35.27      28.06
Discussion    40.85      31.94
Eating        33.78      28.04
Greeting      39.19      31.73
Phoning       38.91      30.76
Photo         45.68      36.31
Posing        41.26      30.40
Purchases     35.19      27.39
Sitting       44.46      34.85
SittingDown   45.59      36.94
Smoking       39.38      32.37
Waiting       39.62      30.36
WalkDog       41.06      33.94
Walking       34.52      28.90
WalkTogether  33.09      27.62
Average      39.1894    31.3077
p1: 39.1894, p2: 31.3077
best epoch:0, best result(mpjpe):inf
0 h 2 mins 37 s
./checkpoint/240107_0917_58
```

The protocol 1 setting: `p1: 39.1894`, shouldn't it be `32.7` like this?

![image](https://github.com/xiu-cs/IGANet/assets/69197635/facb3d40-4545-42f3-b21f-5ebe4af0fc1f)

> BTW, the result of `cpn` 2D points setting is same between paper and my test
```
===Action=== ==p#1 mm== =p#2 mm=
Directions    42.94      34.38
Discussion    47.91      37.36
Eating        44.87      36.13
Greeting      47.68      39.54
Phoning       49.84      39.08
Photo         58.40      44.10
Posing        46.01      36.02
Purchases     44.66      34.13
Sitting       56.76      45.54
SittingDown   61.35      50.16
Smoking       49.31      39.98
Waiting       46.08      35.36
WalkDog       52.01      41.47
Walking       37.57      29.97
WalkTogether  39.84      33.53
Average      48.3483    38.4490
p1: 48.3483, p2: 38.4490
best epoch:0, best result(mpjpe):inf
0 h 2 mins 36 s
./checkpoint/240107_0910_15
```

![image](https://github.com/xiu-cs/IGANet/assets/69197635/56737eee-1bc2-45e7-872e-ca7cf2652238)

And I wanna ask:
> We use § to highlight methods that use refinement module [4, 13].

The `refinement module` is added in the repo? Because I just get `48.3`instead of `47.7`

**Comment by xiu-cs** [comment]
Actually, the pre-trained model I provided is trained on detected 2D pose, not the gt. You need to train the model using gt 2D pose, then you can get the corresponding result (32.7mm). 

The result of 48.3mm was obtained without using the refinement module ( I haven't included the code for refinement,  because I think this part is unnecessary. If you're interested in obtaining the refined result, you can refer to [Modulated GCN](https://github.com/ZhimingZo/Modulated-GCN/blob/main/Modulated_GCN/Modulated-GCN_benchmark/train_graph_time.py).

**Comment by cocoshe** [comment]
> Actually, the pre-trained model I provided is trained on detected 2D pose, not the gt. You need to train the model using gt 2D pose, then you can get the corresponding result (32.7mm).
> 
> The result of 48.3mm was obtained without using the refinement module ( I haven't included the code for refinement, because I think this part is unnecessary. If you're interested in obtaining the refined result, you can refer to [Modulated GCN](https://github.com/ZhimingZo/Modulated-GCN/blob/main/Modulated_GCN/Modulated-GCN_benchmark/train_graph_time.py).

Thanks for your great work and reply! I will try to reproduce the gt result from scratch~

![image](https://github.com/xiu-cs/IGANet/assets/69197635/25f5a44a-673c-4d5a-a0b4-744e3cb3eaf7)

My device is also 1080ti. Do you remember how long will it take to train 20 epochs on your single 1080ti? Maybe it is around 20*20/60=6.666667h.

**Comment by xiu-cs** [comment]
> > Actually, the pre-trained model I provided is trained on detected 2D pose, not the gt. You need to train the model using gt 2D pose, then you can get the corresponding result (32.7mm).
> > The result of 48.3mm was obtained without using the refinement module ( I haven't included the code for refinement, because I think this part is unnecessary. If you're interested in obtaining the refined result, you can refer to [Modulated GCN](https://github.com/ZhimingZo/Modulated-GCN/blob/main/Modulated_GCN/Modulated-GCN_benchmark/train_graph_time.py).
> 
> Thanks for your great work and reply! I will try to reproduce the gt result from scratch~
> 
> ![image](https://private-user-images.githubusercontent.com/69197635/294747963-25f5a44a-673c-4d5a-a0b4-744e3cb3eaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTkzMzMsIm5iZiI6MTcwNDYxOTAzMywicGF0aCI6Ii82OTE5NzYzNS8yOTQ3NDc5NjMtMjVmNWE0NGEtNjczYy00ZDVhLWEwYjQtNzQ0ZTNjYjNlYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA5MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDI4N2FiZjRkYWU3NzI4N2JlNmE5M2U3N2ZmZmJiZjFlZDAyZGFiMzM1ZDExMDA1NTY2ZDg2YzdmMDcwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-qrF-vlD7gwTxAxREo3YpocTS89Nq7dsPZa9kCnZnw)
> 
> My device is also 1080ti. Do you remember how long will it take to train 20 epochs on your single 1080ti? Maybe it is around 20*20/60=6.666667h.

I don't remember the actual time cost, but the time spent per epoch should be similar to yours. There are many factors to completely reproduce the performance, such as graphics card, pytorch, numpy, random seed, etc. Best of luck.

**Comment by cocoshe** [comment]
> > > Actually, the pre-trained model I provided is trained on detected 2D pose, not the gt. You need to train the model using gt 2D pose, then you can get the corresponding result (32.7mm).
> > > The result of 48.3mm was obtained without using the refinement module ( I haven't included the code for refinement, because I think this part is unnecessary. If you're interested in obtaining the refined result, you can refer to [Modulated GCN](https://github.com/ZhimingZo/Modulated-GCN/blob/main/Modulated_GCN/Modulated-GCN_benchmark/train_graph_time.py).
> > 
> > 
> > Thanks for your great work and reply! I will try to reproduce the gt result from scratch~
> > ![image](https://private-user-images.githubusercontent.com/69197635/294747963-25f5a44a-673c-4d5a-a0b4-744e3cb3eaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTkzMzMsIm5iZiI6MTcwNDYxOTAzMywicGF0aCI6Ii82OTE5NzYzNS8yOTQ3NDc5NjMtMjVmNWE0NGEtNjczYy00ZDVhLWEwYjQtNzQ0ZTNjYjNlYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA5MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDI4N2FiZjRkYWU3NzI4N2JlNmE5M2U3N2ZmZmJiZjFlZDAyZGFiMzM1ZDExMDA1NTY2ZDg2YzdmMDcwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-qrF-vlD7gwTxAxREo3YpocTS89Nq7dsPZa9kCnZnw)
> > My device is also 1080ti. Do you remember how long will it take to train 20 epochs on your single 1080ti? Maybe it is around 20*20/60=6.666667h.
> 
> I don't remember the actual time cost, but the time spent per epoch should be similar to yours. There are many factors to completely reproduce the performance, such as graphics card, pytorch, numpy, random seed, etc. Best of luck.

Tks for your work instruction, I reproduced the result with `gt` 2D points input, here's my training log:
```
 1 INFO: Training on 3119616 frames
 2 INFO: Testing on 543360 frames
 3 0
 4 100%|██████████| 24372/24372 [21:29<00:00, 18.91it/s]
 5 100%|██████████| 4245/4245 [02:41<00:00, 26.30it/s]
 6 100%|██████████| 24372/24372 [21:28<00:00, 18.92it/s]
 7 e: 1, lr: 0.0010000, loss: 0.0514, p1: 34.3458, p2: 27.7869
 8 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
 9 100%|██████████| 24372/24372 [21:30<00:00, 18.89it/s]
10 e: 2, lr: 0.0009500, loss: 0.0315, p1: 37.3368, p2: 28.6943
11 100%|██████████| 4245/4245 [02:41<00:00, 26.22it/s]
12 e: 3, lr: 0.0009025, loss: 0.0278, p1: 32.9248, p2: 26.0907
13 100%|██████████| 24372/24372 [21:30<00:00, 18.89it/s]
14 100%|██████████| 4245/4245 [02:42<00:00, 26.17it/s]
15 e: 4, lr: 0.0008574, loss: 0.0258, p1: 40.2011, p2: 29.2491
16 100%|██████████| 24372/24372 [21:29<00:00, 18.89it/s]
17 100%|██████████| 4245/4245 [02:42<00:00, 26.16it/s]
18 100%|██████████| 24372/24372 [21:30<00:00, 18.89it/s]
19 e: 5, lr: 0.0008145, loss: 0.0245, p1: 34.7424, p2: 27.4885
20 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
21 100%|██████████| 24372/24372 [21:34<00:00, 18.83it/s]
22 e: 6, lr: 0.0007738, loss: 0.0234, p1: 33.7428, p2: 26.4654
23 100%|██████████| 4245/4245 [02:42<00:00, 26.11it/s]
24 e: 7, lr: 0.0007351, loss: 0.0227, p1: 33.3353, p2: 26.1024
25 100%|██████████| 24372/24372 [21:34<00:00, 18.82it/s]
26 100%|██████████| 4245/4245 [02:42<00:00, 26.06it/s]
27 e: 8, lr: 0.0006983, loss: 0.0220, p1: 34.8170, p2: 26.7952
28 100%|██████████| 24372/24372 [21:29<00:00, 18.90it/s]
29 100%|██████████| 4245/4245 [02:42<00:00, 26.16it/s]
30 e: 9, lr: 0.0006634, loss: 0.0214, p1: 33.5959, p2: 26.6774
31 100%|██████████| 24372/24372 [21:31<00:00, 18.87it/s]
32 100%|██████████| 4245/4245 [02:42<00:00, 26.15it/s]
33 100%|██████████| 24372/24372 [21:33<00:00, 18.84it/s]
34 e: 10, lr: 0.0006302, loss: 0.0210, p1: 35.4926, p2: 27.5355
35 100%|██████████| 4245/4245 [02:42<00:00, 26.17it/s]
36 100%|██████████| 24372/24372 [21:35<00:00, 18.81it/s]
37 e: 11, lr: 0.0005987, loss: 0.0205, p1: 35.0449, p2: 27.0482
38 100%|██████████| 4245/4245 [02:42<00:00, 26.05it/s]
39 100%|██████████| 24372/24372 [21:35<00:00, 18.82it/s]
40 e: 12, lr: 0.0005688, loss: 0.0202, p1: 32.6875, p2: 25.6963
41 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
42 e: 13, lr: 0.0005404, loss: 0.0198, p1: 36.6595, p2: 27.6827
43 100%|██████████| 24372/24372 [21:34<00:00, 18.82it/s]
44 100%|██████████| 4245/4245 [02:42<00:00, 26.07it/s]
45 e: 14, lr: 0.0005133, loss: 0.0195, p1: 35.7846, p2: 27.3902
46 100%|██████████| 24372/24372 [21:31<00:00, 18.87it/s]
47 100%|██████████| 4245/4245 [02:42<00:00, 26.11it/s]
48 100%|██████████| 24372/24372 [21:32<00:00, 18.85it/s]
49 e: 15, lr: 0.0004877, loss: 0.0193, p1: 35.3870, p2: 27.5433
50 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
51 e: 16, lr: 0.0004633, loss: 0.0190, p1: 35.3196, p2: 26.9495
52 100%|██████████| 24372/24372 [21:33<00:00, 18.84it/s]
53 100%|██████████| 4245/4245 [02:42<00:00, 26.17it/s]
54 100%|██████████| 24372/24372 [21:33<00:00, 18.83it/s]
55 e: 17, lr: 0.0004401, loss: 0.0188, p1: 35.5384, p2: 27.1704
56 100%|██████████| 4245/4245 [02:42<00:00, 26.14it/s]
57 100%|██████████| 24372/24372 [21:32<00:00, 18.85it/s]
58 e: 18, lr: 0.0004181, loss: 0.0186, p1: 35.7506, p2: 27.2244
59 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
60 e: 19, lr: 0.0003972, loss: 0.0184, p1: 34.3835, p2: 26.6431
61 best epoch:12, best result(mpjpe):32.68753744820587
62 7 h 40 mins 38 s
63 ./checkpoint/240107_1740_24
```

`best epoch:12, best result(mpjpe):32.68753744820587`

You had set the seed in your code manually, so the result aligned perfectly.
Tks for your great work again~

**Comment by xiu-cs** [comment]
> > > > Actually, the pre-trained model I provided is trained on detected 2D pose, not the gt. You need to train the model using gt 2D pose, then you can get the corresponding result (32.7mm).
> > > > The result of 48.3mm was obtained without using the refinement module ( I haven't included the code for refinement, because I think this part is unnecessary. If you're interested in obtaining the refined result, you can refer to [Modulated GCN](https://github.com/ZhimingZo/Modulated-GCN/blob/main/Modulated_GCN/Modulated-GCN_benchmark/train_graph_time.py).
> > > 
> > > 
> > > Thanks for your great work and reply! I will try to reproduce the gt result from scratch~
> > > ![image](https://private-user-images.githubusercontent.com/69197635/294747963-25f5a44a-673c-4d5a-a0b4-744e3cb3eaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTkzMzMsIm5iZiI6MTcwNDYxOTAzMywicGF0aCI6Ii82OTE5NzYzNS8yOTQ3NDc5NjMtMjVmNWE0NGEtNjczYy00ZDVhLWEwYjQtNzQ0ZTNjYjNlYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA5MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDI4N2FiZjRkYWU3NzI4N2JlNmE5M2U3N2ZmZmJiZjFlZDAyZGFiMzM1ZDExMDA1NTY2ZDg2YzdmMDcwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-qrF-vlD7gwTxAxREo3YpocTS89Nq7dsPZa9kCnZnw)
> > > My device is also 1080ti. Do you remember how long will it take to train 20 epochs on your single 1080ti? Maybe it is around 20*20/60=6.666667h.
> > 
> > 
> > I don't remember the actual time cost, but the time spent per epoch should be similar to yours. There are many factors to completely reproduce the performance, such as graphics card, pytorch, numpy, random seed, etc. Best of luck.
> 
> Tks for your work instruction, I reproduced the result with `gt` 2D points input, here's my training log:
> 
> ```
>  1 INFO: Training on 3119616 frames
>  2 INFO: Testing on 543360 frames
>  3 0
>  4 100%|██████████| 24372/24372 [21:29<00:00, 18.91it/s]
>  5 100%|██████████| 4245/4245 [02:41<00:00, 26.30it/s]
>  6 100%|██████████| 24372/24372 [21:28<00:00, 18.92it/s]
>  7 e: 1, lr: 0.0010000, loss: 0.0514, p1: 34.3458, p2: 27.7869
>  8 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
>  9 100%|██████████| 24372/24372 [21:30<00:00, 18.89it/s]
> 10 e: 2, lr: 0.0009500, loss: 0.0315, p1: 37.3368, p2: 28.6943
> 11 100%|██████████| 4245/4245 [02:41<00:00, 26.22it/s]
> 12 e: 3, lr: 0.0009025, loss: 0.0278, p1: 32.9248, p2: 26.0907
> 13 100%|██████████| 24372/24372 [21:30<00:00, 18.89it/s]
> 14 100%|██████████| 4245/4245 [02:42<00:00, 26.17it/s]
> 15 e: 4, lr: 0.0008574, loss: 0.0258, p1: 40.2011, p2: 29.2491
> 16 100%|██████████| 24372/24372 [21:29<00:00, 18.89it/s]
> 17 100%|██████████| 4245/4245 [02:42<00:00, 26.16it/s]
> 18 100%|██████████| 24372/24372 [21:30<00:00, 18.89it/s]
> 19 e: 5, lr: 0.0008145, loss: 0.0245, p1: 34.7424, p2: 27.4885
> 20 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
> 21 100%|██████████| 24372/24372 [21:34<00:00, 18.83it/s]
> 22 e: 6, lr: 0.0007738, loss: 0.0234, p1: 33.7428, p2: 26.4654
> 23 100%|██████████| 4245/4245 [02:42<00:00, 26.11it/s]
> 24 e: 7, lr: 0.0007351, loss: 0.0227, p1: 33.3353, p2: 26.1024
> 25 100%|██████████| 24372/24372 [21:34<00:00, 18.82it/s]
> 26 100%|██████████| 4245/4245 [02:42<00:00, 26.06it/s]
> 27 e: 8, lr: 0.0006983, loss: 0.0220, p1: 34.8170, p2: 26.7952
> 28 100%|██████████| 24372/24372 [21:29<00:00, 18.90it/s]
> 29 100%|██████████| 4245/4245 [02:42<00:00, 26.16it/s]
> 30 e: 9, lr: 0.0006634, loss: 0.0214, p1: 33.5959, p2: 26.6774
> 31 100%|██████████| 24372/24372 [21:31<00:00, 18.87it/s]
> 32 100%|██████████| 4245/4245 [02:42<00:00, 26.15it/s]
> 33 100%|██████████| 24372/24372 [21:33<00:00, 18.84it/s]
> 34 e: 10, lr: 0.0006302, loss: 0.0210, p1: 35.4926, p2: 27.5355
> 35 100%|██████████| 4245/4245 [02:42<00:00, 26.17it/s]
> 36 100%|██████████| 24372/24372 [21:35<00:00, 18.81it/s]
> 37 e: 11, lr: 0.0005987, loss: 0.0205, p1: 35.0449, p2: 27.0482
> 38 100%|██████████| 4245/4245 [02:42<00:00, 26.05it/s]
> 39 100%|██████████| 24372/24372 [21:35<00:00, 18.82it/s]
> 40 e: 12, lr: 0.0005688, loss: 0.0202, p1: 32.6875, p2: 25.6963
> 41 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
> 42 e: 13, lr: 0.0005404, loss: 0.0198, p1: 36.6595, p2: 27.6827
> 43 100%|██████████| 24372/24372 [21:34<00:00, 18.82it/s]
> 44 100%|██████████| 4245/4245 [02:42<00:00, 26.07it/s]
> 45 e: 14, lr: 0.0005133, loss: 0.0195, p1: 35.7846, p2: 27.3902
> 46 100%|██████████| 24372/24372 [21:31<00:00, 18.87it/s]
> 47 100%|██████████| 4245/4245 [02:42<00:00, 26.11it/s]
> 48 100%|██████████| 24372/24372 [21:32<00:00, 18.85it/s]
> 49 e: 15, lr: 0.0004877, loss: 0.0193, p1: 35.3870, p2: 27.5433
> 50 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
> 51 e: 16, lr: 0.0004633, loss: 0.0190, p1: 35.3196, p2: 26.9495
> 52 100%|██████████| 24372/24372 [21:33<00:00, 18.84it/s]
> 53 100%|██████████| 4245/4245 [02:42<00:00, 26.17it/s]
> 54 100%|██████████| 24372/24372 [21:33<00:00, 18.83it/s]
> 55 e: 17, lr: 0.0004401, loss: 0.0188, p1: 35.5384, p2: 27.1704
> 56 100%|██████████| 4245/4245 [02:42<00:00, 26.14it/s]
> 57 100%|██████████| 24372/24372 [21:32<00:00, 18.85it/s]
> 58 e: 18, lr: 0.0004181, loss: 0.0186, p1: 35.7506, p2: 27.2244
> 59 100%|██████████| 4245/4245 [02:42<00:00, 26.12it/s]
> 60 e: 19, lr: 0.0003972, loss: 0.0184, p1: 34.3835, p2: 26.6431
> 61 best epoch:12, best result(mpjpe):32.68753744820587
> 62 7 h 40 mins 38 s
> 63 ./checkpoint/240107_1740_24
> ```
> 
> `best epoch:12, best result(mpjpe):32.68753744820587`
> 
> You had set the seed in your code manually, so the result aligned perfectly. Tks for your great work again~

Great! Thank you for your interest in my work. If you have any further questions, feel free to contact me.
